
version: '3.8'

services:
  db:
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  db-data:
